<?php
/**
 * Storefront widget labels — cs_CZ.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Upřesnit výsledky',
  'refine' => 'Upřesnit',
  'in_stock' => 'Skladem',
  'on_sale' => 'Ve slevě',
  'brand' => 'Značka',
  'category' => 'Kategorie',
  'view' => 'Zobrazit',
  'add_to_cart' => 'Přidat do košíku',
  'adding' => 'Přidávání…',
  'added' => 'Přidáno ✓',
  'try_again' => 'Zkusit znovu',
  'searching' => 'Vyhledávání…',
  'unavailable_brief' => 'Vyhledávání není k dispozici.',
  'unavailable' => 'Vyhledávání teď není k dispozici.',
  'no_products' => 'Nebyly nalezeny žádné produkty.',
  'no_products_for' => 'Pro „%s“ nebyly nalezeny žádné produkty.',
  'nothing_found' => 'Pro „%s“ nebylo nic nalezeno.',
  'placeholder' => 'Hledat produkty…',
  'close_search' => 'Zavřít vyhledávání',
  'product_results' => 'Nalezené produkty',
  'recent_searches' => 'Nedávno hledané',
  'clear' => 'Vymazat',
  'start_typing' => 'Začněte psát a vyhledejte produkty…',
  'sale' => 'Sleva',
  'out_of_stock' => 'Není skladem',
  'pages_posts' => 'Stránky a příspěvky',
  'page' => 'Stránka',
  'article' => 'Článek',
  'ms' => '%s ms',
  'powered_by' => 'Používá NitroSearch',
  'page_of' => 'Stránka %1$s z %2$s',
  'prev' => '← Předchozí',
  'next' => 'Další →',
  'products_found' => 
  array (
    'one' => 'Nalezen %s produkt.',
    'few' => 'Nalezeny %s produkty.',
    'many' => 'Nalezeno %s produktů.',
    'other' => 'Nalezeno %s produktů.',
  ),
  'see_all' => 
  array (
    'one' => 'Zobrazit %s výsledek →',
    'few' => 'Zobrazit všechny %s výsledky →',
    'many' => 'Zobrazit všech %s výsledků →',
    'other' => 'Zobrazit všech %s výsledků →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s výsledek pro „%2$s“',
    'few' => '%1$s výsledky pro „%2$s“',
    'many' => '%1$s výsledků pro „%2$s“',
    'other' => '%1$s výsledků pro „%2$s“',
  ),
  'results_count' => 
  array (
    'one' => '%s výsledek',
    'few' => '%s výsledky',
    'many' => '%s výsledků',
    'other' => '%s výsledků',
  ),
);
