<?php
/**
 * Storefront widget labels — da_DK.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Afgræns resultater',
  'refine' => 'Afgræns',
  'in_stock' => 'På lager',
  'on_sale' => 'På tilbud',
  'brand' => 'Mærke',
  'category' => 'Kategori',
  'view' => 'Vis',
  'add_to_cart' => 'Tilføj til kurv',
  'adding' => 'Tilføjer…',
  'added' => 'Tilføjet ✓',
  'try_again' => 'Prøv igen',
  'searching' => 'Søger…',
  'unavailable_brief' => 'Søgningen er ikke tilgængelig.',
  'unavailable' => 'Søgningen er ikke tilgængelig lige nu.',
  'no_products' => 'Ingen produkter fundet.',
  'no_products_for' => 'Ingen produkter fundet for ”%s”.',
  'nothing_found' => 'Intet fundet for ”%s”.',
  'placeholder' => 'Søg efter produkter…',
  'close_search' => 'Luk søgning',
  'product_results' => 'Produktresultater',
  'recent_searches' => 'Seneste søgninger',
  'clear' => 'Ryd',
  'start_typing' => 'Begynd at skrive for at søge efter produkter…',
  'sale' => 'Tilbud',
  'out_of_stock' => 'Ikke på lager',
  'pages_posts' => 'Sider & indlæg',
  'page' => 'Side',
  'article' => 'Artikel',
  'ms' => '%s ms',
  'powered_by' => 'Drevet af NitroSearch',
  'page_of' => 'Side %1$s af %2$s',
  'prev' => '← Forrige',
  'next' => 'Næste →',
  'products_found' => 
  array (
    'one' => '%s produkt fundet.',
    'few' => '%s produkter fundet.',
    'many' => '%s produkter fundet.',
    'other' => '%s produkter fundet.',
  ),
  'see_all' => 
  array (
    'one' => 'Se %s resultat →',
    'few' => 'Se alle %s resultater →',
    'many' => 'Se alle %s resultater →',
    'other' => 'Se alle %s resultater →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s resultat for ”%2$s”',
    'few' => '%1$s resultater for ”%2$s”',
    'many' => '%1$s resultater for ”%2$s”',
    'other' => '%1$s resultater for ”%2$s”',
  ),
  'results_count' => 
  array (
    'one' => '%s resultat',
    'few' => '%s resultater',
    'many' => '%s resultater',
    'other' => '%s resultater',
  ),
);
