<?php
/**
 * Storefront widget labels — de_DE.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Ergebnisse filtern',
  'refine' => 'Filtern',
  'in_stock' => 'Vorrätig',
  'on_sale' => 'Im Angebot',
  'brand' => 'Marke',
  'category' => 'Kategorie',
  'view' => 'Anzeigen',
  'add_to_cart' => 'In den Warenkorb',
  'adding' => 'Wird hinzugefügt …',
  'added' => 'Hinzugefügt ✓',
  'try_again' => 'Erneut versuchen',
  'searching' => 'Suche läuft …',
  'unavailable_brief' => 'Die Suche ist nicht verfügbar.',
  'unavailable' => 'Die Suche ist gerade nicht verfügbar.',
  'no_products' => 'Keine Produkte gefunden.',
  'no_products_for' => 'Keine Produkte für „%s“ gefunden.',
  'nothing_found' => 'Nichts für „%s“ gefunden.',
  'placeholder' => 'Produkte suchen …',
  'close_search' => 'Suche schließen',
  'product_results' => 'Produktergebnisse',
  'recent_searches' => 'Letzte Suchanfragen',
  'clear' => 'Löschen',
  'start_typing' => 'Tippe los, um Produkte zu suchen …',
  'sale' => 'Angebot',
  'out_of_stock' => 'Nicht vorrätig',
  'pages_posts' => 'Seiten und Beiträge',
  'page' => 'Seite',
  'article' => 'Beitrag',
  'ms' => '%s ms',
  'powered_by' => 'Präsentiert von NitroSearch',
  'page_of' => 'Seite %1$s von %2$s',
  'prev' => '← Zurück',
  'next' => 'Weiter →',
  'products_found' => 
  array (
    'one' => '%s Produkt gefunden.',
    'few' => '%s Produkte gefunden.',
    'many' => '%s Produkte gefunden.',
    'other' => '%s Produkte gefunden.',
  ),
  'see_all' => 
  array (
    'one' => '%s Ergebnis ansehen →',
    'few' => 'Alle %s Ergebnisse ansehen →',
    'many' => 'Alle %s Ergebnisse ansehen →',
    'other' => 'Alle %s Ergebnisse ansehen →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s Ergebnis für „%2$s“',
    'few' => '%1$s Ergebnisse für „%2$s“',
    'many' => '%1$s Ergebnisse für „%2$s“',
    'other' => '%1$s Ergebnisse für „%2$s“',
  ),
  'results_count' => 
  array (
    'one' => '%s Ergebnis',
    'few' => '%s Ergebnisse',
    'many' => '%s Ergebnisse',
    'other' => '%s Ergebnisse',
  ),
);
