<?php
/**
 * Storefront widget labels — el.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Φιλτράρισμα αποτελεσμάτων',
  'refine' => 'Φιλτράρισμα',
  'in_stock' => 'Σε απόθεμα',
  'on_sale' => 'Σε προσφορά',
  'brand' => 'Μάρκα',
  'category' => 'Κατηγορία',
  'view' => 'Προβολή',
  'add_to_cart' => 'Προσθήκη στο καλάθι',
  'adding' => 'Γίνεται προσθήκη…',
  'added' => 'Προστέθηκε ✓',
  'try_again' => 'Δοκιμάστε ξανά',
  'searching' => 'Αναζήτηση…',
  'unavailable_brief' => 'Η αναζήτηση δεν είναι διαθέσιμη.',
  'unavailable' => 'Η αναζήτηση δεν είναι διαθέσιμη αυτήν τη στιγμή.',
  'no_products' => 'Δεν βρέθηκαν προϊόντα.',
  'no_products_for' => 'Δεν βρέθηκαν προϊόντα για «%s».',
  'nothing_found' => 'Δεν βρέθηκε τίποτα για «%s».',
  'placeholder' => 'Αναζήτηση προϊόντων…',
  'close_search' => 'Κλείσιμο αναζήτησης',
  'product_results' => 'Αποτελέσματα προϊόντων',
  'recent_searches' => 'Πρόσφατες αναζητήσεις',
  'clear' => 'Καθαρισμός',
  'start_typing' => 'Ξεκινήστε να πληκτρολογείτε για αναζήτηση προϊόντων…',
  'sale' => 'Προσφορά',
  'out_of_stock' => 'Εξαντλημένο',
  'pages_posts' => 'Σελίδες & άρθρα',
  'page' => 'Σελίδα',
  'article' => 'Άρθρο',
  'ms' => '%s ms',
  'powered_by' => 'Με την τεχνολογία του NitroSearch',
  'page_of' => 'Σελίδα %1$s από %2$s',
  'prev' => '← Προηγούμενη',
  'next' => 'Επόμενη →',
  'products_found' => 
  array (
    'one' => 'Βρέθηκε %s προϊόν.',
    'few' => 'Βρέθηκαν %s προϊόντα.',
    'many' => 'Βρέθηκαν %s προϊόντα.',
    'other' => 'Βρέθηκαν %s προϊόντα.',
  ),
  'see_all' => 
  array (
    'one' => 'Δείτε το %s αποτέλεσμα →',
    'few' => 'Δείτε όλα τα %s αποτελέσματα →',
    'many' => 'Δείτε όλα τα %s αποτελέσματα →',
    'other' => 'Δείτε όλα τα %s αποτελέσματα →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s αποτέλεσμα για «%2$s»',
    'few' => '%1$s αποτελέσματα για «%2$s»',
    'many' => '%1$s αποτελέσματα για «%2$s»',
    'other' => '%1$s αποτελέσματα για «%2$s»',
  ),
  'results_count' => 
  array (
    'one' => '%s αποτέλεσμα',
    'few' => '%s αποτελέσματα',
    'many' => '%s αποτελέσματα',
    'other' => '%s αποτελέσματα',
  ),
);
