<?php
/**
 * Storefront widget labels — en_GB.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Refine results',
  'refine' => 'Refine',
  'in_stock' => 'In stock',
  'on_sale' => 'On sale',
  'brand' => 'Brand',
  'category' => 'Category',
  'view' => 'View',
  'add_to_cart' => 'Add to basket',
  'adding' => 'Adding…',
  'added' => 'Added ✓',
  'try_again' => 'Try again',
  'searching' => 'Searching…',
  'unavailable_brief' => 'Search is unavailable.',
  'unavailable' => 'Search is unavailable right now.',
  'no_products' => 'No products found.',
  'no_products_for' => 'No products found for “%s”.',
  'nothing_found' => 'Nothing found for “%s”.',
  'placeholder' => 'Search products…',
  'close_search' => 'Close search',
  'product_results' => 'Product results',
  'recent_searches' => 'Recent searches',
  'clear' => 'Clear',
  'start_typing' => 'Start typing to search products…',
  'sale' => 'Sale',
  'out_of_stock' => 'Out of stock',
  'pages_posts' => 'Pages & posts',
  'page' => 'Page',
  'article' => 'Article',
  'ms' => '%s ms',
  'powered_by' => 'Powered by NitroSearch',
  'page_of' => 'Page %1$s of %2$s',
  'prev' => '← Prev',
  'next' => 'Next →',
  'products_found' => 
  array (
    'one' => '%s product found.',
    'few' => '%s products found.',
    'many' => '%s products found.',
    'other' => '%s products found.',
  ),
  'see_all' => 
  array (
    'one' => 'See all %s result →',
    'few' => 'See all %s results →',
    'many' => 'See all %s results →',
    'other' => 'See all %s results →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s result for “%2$s”',
    'few' => '%1$s results for “%2$s”',
    'many' => '%1$s results for “%2$s”',
    'other' => '%1$s results for “%2$s”',
  ),
  'results_count' => 
  array (
    'one' => '%s result',
    'few' => '%s results',
    'many' => '%s results',
    'other' => '%s results',
  ),
);
