<?php
/**
 * Storefront widget labels — es_ES.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Refinar resultados',
  'refine' => 'Refinar',
  'in_stock' => 'En stock',
  'on_sale' => 'En oferta',
  'brand' => 'Marca',
  'category' => 'Categoría',
  'view' => 'Ver',
  'add_to_cart' => 'Añadir al carrito',
  'adding' => 'Añadiendo…',
  'added' => 'Añadido ✓',
  'try_again' => 'Reintentar',
  'searching' => 'Buscando…',
  'unavailable_brief' => 'La búsqueda no está disponible.',
  'unavailable' => 'La búsqueda no está disponible en este momento.',
  'no_products' => 'No se han encontrado productos.',
  'no_products_for' => 'No se han encontrado productos para «%s».',
  'nothing_found' => 'No se ha encontrado nada para «%s».',
  'placeholder' => 'Buscar productos…',
  'close_search' => 'Cerrar la búsqueda',
  'product_results' => 'Resultados de productos',
  'recent_searches' => 'Búsquedas recientes',
  'clear' => 'Borrar',
  'start_typing' => 'Empieza a escribir para buscar productos…',
  'sale' => 'Oferta',
  'out_of_stock' => 'Agotado',
  'pages_posts' => 'Páginas y entradas',
  'page' => 'Página',
  'article' => 'Artículo',
  'ms' => '%s ms',
  'powered_by' => 'Con la tecnología de NitroSearch',
  'page_of' => 'Página %1$s de %2$s',
  'prev' => '← Anterior',
  'next' => 'Siguiente →',
  'products_found' => 
  array (
    'one' => 'Se ha encontrado %s producto.',
    'few' => 'Se han encontrado %s productos.',
    'many' => 'Se han encontrado %s productos.',
    'other' => 'Se han encontrado %s productos.',
  ),
  'see_all' => 
  array (
    'one' => 'Ver %s resultado →',
    'few' => 'Ver los %s resultados →',
    'many' => 'Ver los %s resultados →',
    'other' => 'Ver los %s resultados →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s resultado para «%2$s»',
    'few' => '%1$s resultados para «%2$s»',
    'many' => '%1$s resultados para «%2$s»',
    'other' => '%1$s resultados para «%2$s»',
  ),
  'results_count' => 
  array (
    'one' => '%s resultado',
    'few' => '%s resultados',
    'many' => '%s resultados',
    'other' => '%s resultados',
  ),
);
