<?php
/**
 * Storefront widget labels — fi.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Tarkenna tuloksia',
  'refine' => 'Tarkenna',
  'in_stock' => 'Varastossa',
  'on_sale' => 'Alennuksessa',
  'brand' => 'Tuotemerkki',
  'category' => 'Osasto',
  'view' => 'Näytä',
  'add_to_cart' => 'Lisää ostoskoriin',
  'adding' => 'Lisätään…',
  'added' => 'Lisätty ✓',
  'try_again' => 'Yritä uudelleen',
  'searching' => 'Haetaan…',
  'unavailable_brief' => 'Haku ei ole käytettävissä.',
  'unavailable' => 'Haku ei ole juuri nyt käytettävissä.',
  'no_products' => 'Tuotteita ei löytynyt.',
  'no_products_for' => 'Tuotteita ei löytynyt haulla ”%s”.',
  'nothing_found' => 'Mitään ei löytynyt haulla ”%s”.',
  'placeholder' => 'Hae tuotteita…',
  'close_search' => 'Sulje haku',
  'product_results' => 'Tuotetulokset',
  'recent_searches' => 'Viimeisimmät haut',
  'clear' => 'Tyhjennä',
  'start_typing' => 'Aloita kirjoittaminen hakeaksesi tuotteita…',
  'sale' => 'Ale',
  'out_of_stock' => 'Loppu varastosta',
  'pages_posts' => 'Sivut ja artikkelit',
  'page' => 'Sivu',
  'article' => 'Artikkeli',
  'ms' => '%s ms',
  'powered_by' => 'Palvelun tarjoaa NitroSearch',
  'page_of' => 'Sivu %1$s / %2$s',
  'prev' => '← Edellinen',
  'next' => 'Seuraava →',
  'products_found' => 
  array (
    'one' => '%s tuote löytyi.',
    'few' => '%s tuotetta löytyi.',
    'many' => '%s tuotetta löytyi.',
    'other' => '%s tuotetta löytyi.',
  ),
  'see_all' => 
  array (
    'one' => 'Näytä %s tulos →',
    'few' => 'Näytä kaikki %s tulosta →',
    'many' => 'Näytä kaikki %s tulosta →',
    'other' => 'Näytä kaikki %s tulosta →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s tulos haulle ”%2$s”',
    'few' => '%1$s tulosta haulle ”%2$s”',
    'many' => '%1$s tulosta haulle ”%2$s”',
    'other' => '%1$s tulosta haulle ”%2$s”',
  ),
  'results_count' => 
  array (
    'one' => '%s tulos',
    'few' => '%s tulosta',
    'many' => '%s tulosta',
    'other' => '%s tulosta',
  ),
);
