<?php
/**
 * Storefront widget labels — fr_FR.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Affiner les résultats',
  'refine' => 'Affiner',
  'in_stock' => 'En stock',
  'on_sale' => 'En promotion',
  'brand' => 'Marque',
  'category' => 'Catégorie',
  'view' => 'Voir',
  'add_to_cart' => 'Ajouter au panier',
  'adding' => 'Ajout…',
  'added' => 'Ajouté ✓',
  'try_again' => 'Réessayer',
  'searching' => 'Recherche en cours…',
  'unavailable_brief' => 'La recherche est indisponible.',
  'unavailable' => 'La recherche est indisponible pour le moment.',
  'no_products' => 'Aucun produit trouvé.',
  'no_products_for' => 'Aucun produit trouvé pour « %s ».',
  'nothing_found' => 'Aucun résultat pour « %s ».',
  'placeholder' => 'Rechercher des produits…',
  'close_search' => 'Fermer la recherche',
  'product_results' => 'Résultats produits',
  'recent_searches' => 'Recherches récentes',
  'clear' => 'Effacer',
  'start_typing' => 'Commencez à taper pour rechercher des produits…',
  'sale' => 'Promo',
  'out_of_stock' => 'Rupture de stock',
  'pages_posts' => 'Pages et articles',
  'page' => 'Page',
  'article' => 'Article',
  'ms' => '%s ms',
  'powered_by' => 'Propulsé par NitroSearch',
  'page_of' => 'Page %1$s sur %2$s',
  'prev' => '← Préc.',
  'next' => 'Suivant →',
  'products_found' => 
  array (
    'one' => '%s produit trouvé.',
    'few' => '%s produits trouvés.',
    'many' => '%s produits trouvés.',
    'other' => '%s produits trouvés.',
  ),
  'see_all' => 
  array (
    'one' => 'Voir %s résultat →',
    'few' => 'Voir les %s résultats →',
    'many' => 'Voir les %s résultats →',
    'other' => 'Voir les %s résultats →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s résultat pour « %2$s »',
    'few' => '%1$s résultats pour « %2$s »',
    'many' => '%1$s résultats pour « %2$s »',
    'other' => '%1$s résultats pour « %2$s »',
  ),
  'results_count' => 
  array (
    'one' => '%s résultat',
    'few' => '%s résultats',
    'many' => '%s résultats',
    'other' => '%s résultats',
  ),
);
