<?php
/**
 * Storefront widget labels — id_ID.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Persempit hasil',
  'refine' => 'Persempit',
  'in_stock' => 'Stok tersedia',
  'on_sale' => 'Sedang diskon',
  'brand' => 'Merek',
  'category' => 'Kategori',
  'view' => 'Lihat',
  'add_to_cart' => 'Tambahkan ke keranjang',
  'adding' => 'Menambahkan…',
  'added' => 'Ditambahkan ✓',
  'try_again' => 'Coba lagi',
  'searching' => 'Mencari…',
  'unavailable_brief' => 'Pencarian tidak tersedia.',
  'unavailable' => 'Pencarian sedang tidak tersedia.',
  'no_products' => 'Tidak ada produk yang ditemukan.',
  'no_products_for' => 'Tidak ada produk yang ditemukan untuk “%s”.',
  'nothing_found' => 'Tidak ada yang ditemukan untuk “%s”.',
  'placeholder' => 'Cari produk…',
  'close_search' => 'Tutup pencarian',
  'product_results' => 'Hasil produk',
  'recent_searches' => 'Pencarian terbaru',
  'clear' => 'Hapus',
  'start_typing' => 'Mulai ketik untuk mencari produk…',
  'sale' => 'Diskon',
  'out_of_stock' => 'Stok habis',
  'pages_posts' => 'Halaman & pos',
  'page' => 'Halaman',
  'article' => 'Artikel',
  'ms' => '%s ms',
  'powered_by' => 'Didukung oleh NitroSearch',
  'page_of' => 'Halaman %1$s dari %2$s',
  'prev' => '← Sebelumnya',
  'next' => 'Berikutnya →',
  'products_found' => 
  array (
    'other' => '%s produk ditemukan.',
  ),
  'see_all' => 
  array (
    'other' => 'Lihat semua %s hasil →',
  ),
  'results_for' => 
  array (
    'other' => '%1$s hasil untuk “%2$s”',
  ),
  'results_count' => 
  array (
    'other' => '%s hasil',
  ),
);
