<?php
/**
 * Storefront widget labels — it_IT.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Affina i risultati',
  'refine' => 'Affina',
  'in_stock' => 'Disponibile',
  'on_sale' => 'In offerta',
  'brand' => 'Marchio',
  'category' => 'Categoria',
  'view' => 'Vedi',
  'add_to_cart' => 'Aggiungi al carrello',
  'adding' => 'Aggiunta in corso…',
  'added' => 'Aggiunto ✓',
  'try_again' => 'Riprova',
  'searching' => 'Ricerca in corso…',
  'unavailable_brief' => 'La ricerca non è disponibile.',
  'unavailable' => 'La ricerca non è disponibile in questo momento.',
  'no_products' => 'Nessun prodotto trovato.',
  'no_products_for' => 'Nessun prodotto trovato per «%s».',
  'nothing_found' => 'Nessun risultato per «%s».',
  'placeholder' => 'Cerca prodotti…',
  'close_search' => 'Chiudi la ricerca',
  'product_results' => 'Risultati dei prodotti',
  'recent_searches' => 'Ricerche recenti',
  'clear' => 'Cancella',
  'start_typing' => 'Inizia a digitare per cercare i prodotti…',
  'sale' => 'In offerta',
  'out_of_stock' => 'Esaurito',
  'pages_posts' => 'Pagine e articoli',
  'page' => 'Pagina',
  'article' => 'Articolo',
  'ms' => '%s ms',
  'powered_by' => 'Powered by NitroSearch',
  'page_of' => 'Pagina %1$s di %2$s',
  'prev' => '← Precedente',
  'next' => 'Successivo →',
  'products_found' => 
  array (
    'one' => '%s prodotto trovato.',
    'few' => '%s prodotti trovati.',
    'many' => '%s prodotti trovati.',
    'other' => '%s prodotti trovati.',
  ),
  'see_all' => 
  array (
    'one' => 'Vedi %s risultato →',
    'few' => 'Vedi tutti i %s risultati →',
    'many' => 'Vedi tutti i %s risultati →',
    'other' => 'Vedi tutti i %s risultati →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s risultato per «%2$s»',
    'few' => '%1$s risultati per «%2$s»',
    'many' => '%1$s risultati per «%2$s»',
    'other' => '%1$s risultati per «%2$s»',
  ),
  'results_count' => 
  array (
    'one' => '%s risultato',
    'few' => '%s risultati',
    'many' => '%s risultati',
    'other' => '%s risultati',
  ),
);
