<?php
/**
 * Storefront widget labels — ja.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => '結果を絞り込む',
  'refine' => '絞り込み',
  'in_stock' => '在庫あり',
  'on_sale' => 'セール中',
  'brand' => 'ブランド',
  'category' => 'カテゴリー',
  'view' => '表示',
  'add_to_cart' => 'カートに追加',
  'adding' => '追加中…',
  'added' => '追加しました ✓',
  'try_again' => '再試行',
  'searching' => '検索中…',
  'unavailable_brief' => '検索は利用できません。',
  'unavailable' => '現在、検索を利用できません。',
  'no_products' => '商品が見つかりませんでした。',
  'no_products_for' => '「%s」に一致する商品は見つかりませんでした。',
  'nothing_found' => '「%s」に一致するものは見つかりませんでした。',
  'placeholder' => '商品を検索…',
  'close_search' => '検索を閉じる',
  'product_results' => '商品の検索結果',
  'recent_searches' => '最近の検索',
  'clear' => 'クリア',
  'start_typing' => '文字を入力して商品を検索…',
  'sale' => 'セール',
  'out_of_stock' => '在庫切れ',
  'pages_posts' => '固定ページと投稿',
  'page' => '固定ページ',
  'article' => '記事',
  'ms' => '%s ms',
  'powered_by' => 'Powered by NitroSearch',
  'page_of' => '%2$sページ中%1$sページ目',
  'prev' => '← 前へ',
  'next' => '次へ →',
  'products_found' => 
  array (
    'other' => '%s件の商品が見つかりました。',
  ),
  'see_all' => 
  array (
    'other' => '%s件の結果をすべて見る →',
  ),
  'results_for' => 
  array (
    'other' => '「%2$s」の検索結果: %1$s件',
  ),
  'results_count' => 
  array (
    'other' => '%s件の結果',
  ),
);
