<?php
/**
 * Storefront widget labels — nb_NO.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Avgrens resultatene',
  'refine' => 'Avgrens',
  'in_stock' => 'På lager',
  'on_sale' => 'På tilbud',
  'brand' => 'Merke',
  'category' => 'Kategori',
  'view' => 'Vis',
  'add_to_cart' => 'Legg i handlekurv',
  'adding' => 'Legger til …',
  'added' => 'Lagt til ✓',
  'try_again' => 'Prøv igjen',
  'searching' => 'Søker …',
  'unavailable_brief' => 'Søket er utilgjengelig.',
  'unavailable' => 'Søket er utilgjengelig akkurat nå.',
  'no_products' => 'Fant ingen produkter.',
  'no_products_for' => 'Fant ingen produkter for «%s».',
  'nothing_found' => 'Fant ingenting for «%s».',
  'placeholder' => 'Søk etter produkter …',
  'close_search' => 'Lukk søket',
  'product_results' => 'Produktresultater',
  'recent_searches' => 'Nylige søk',
  'clear' => 'Tøm',
  'start_typing' => 'Begynn å skrive for å søke etter produkter …',
  'sale' => 'Tilbud',
  'out_of_stock' => 'Ikke på lager',
  'pages_posts' => 'Sider og innlegg',
  'page' => 'Side',
  'article' => 'Artikkel',
  'ms' => '%s ms',
  'powered_by' => 'Levert av NitroSearch',
  'page_of' => 'Side %1$s av %2$s',
  'prev' => '← Forrige',
  'next' => 'Neste →',
  'products_found' => 
  array (
    'one' => '%s produkt funnet.',
    'few' => '%s produkter funnet.',
    'many' => '%s produkter funnet.',
    'other' => '%s produkter funnet.',
  ),
  'see_all' => 
  array (
    'one' => 'Se %s resultat →',
    'few' => 'Se alle %s resultater →',
    'many' => 'Se alle %s resultater →',
    'other' => 'Se alle %s resultater →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s resultat for «%2$s»',
    'few' => '%1$s resultater for «%2$s»',
    'many' => '%1$s resultater for «%2$s»',
    'other' => '%1$s resultater for «%2$s»',
  ),
  'results_count' => 
  array (
    'one' => '%s resultat',
    'few' => '%s resultater',
    'many' => '%s resultater',
    'other' => '%s resultater',
  ),
);
