<?php
/**
 * Storefront widget labels — nl_NL.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Resultaten verfijnen',
  'refine' => 'Verfijnen',
  'in_stock' => 'Op voorraad',
  'on_sale' => 'In de uitverkoop',
  'brand' => 'Merk',
  'category' => 'Categorie',
  'view' => 'Bekijken',
  'add_to_cart' => 'Toevoegen aan winkelwagen',
  'adding' => 'Aan het toevoegen…',
  'added' => 'Toegevoegd ✓',
  'try_again' => 'Opnieuw proberen',
  'searching' => 'Aan het zoeken...',
  'unavailable_brief' => 'Zoeken is niet beschikbaar.',
  'unavailable' => 'Zoeken is op dit moment niet beschikbaar.',
  'no_products' => 'Geen producten gevonden.',
  'no_products_for' => 'Geen producten gevonden voor ‘%s’.',
  'nothing_found' => 'Niets gevonden voor ‘%s’.',
  'placeholder' => 'Producten zoeken…',
  'close_search' => 'Zoeken sluiten',
  'product_results' => 'Productresultaten',
  'recent_searches' => 'Recente zoekopdrachten',
  'clear' => 'Wissen',
  'start_typing' => 'Begin met typen om producten te zoeken…',
  'sale' => 'Uitverkoop',
  'out_of_stock' => 'Uitverkocht',
  'pages_posts' => 'Pagina\'s en berichten',
  'page' => 'Pagina',
  'article' => 'Artikel',
  'ms' => '%s ms',
  'powered_by' => 'Mogelijk gemaakt door NitroSearch',
  'page_of' => 'Pagina %1$s van %2$s',
  'prev' => '← Vorige',
  'next' => 'Volgende →',
  'products_found' => 
  array (
    'one' => '%s product gevonden.',
    'few' => '%s producten gevonden.',
    'many' => '%s producten gevonden.',
    'other' => '%s producten gevonden.',
  ),
  'see_all' => 
  array (
    'one' => 'Bekijk %s resultaat →',
    'few' => 'Bekijk alle %s resultaten →',
    'many' => 'Bekijk alle %s resultaten →',
    'other' => 'Bekijk alle %s resultaten →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s resultaat voor ‘%2$s’',
    'few' => '%1$s resultaten voor ‘%2$s’',
    'many' => '%1$s resultaten voor ‘%2$s’',
    'other' => '%1$s resultaten voor ‘%2$s’',
  ),
  'results_count' => 
  array (
    'one' => '%s resultaat',
    'few' => '%s resultaten',
    'many' => '%s resultaten',
    'other' => '%s resultaten',
  ),
);
