<?php
/**
 * Storefront widget labels — pl_PL.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Zawęź wyniki',
  'refine' => 'Zawęź',
  'in_stock' => 'Na stanie',
  'on_sale' => 'W promocji',
  'brand' => 'Marka',
  'category' => 'Kategoria',
  'view' => 'Zobacz',
  'add_to_cart' => 'Dodaj do koszyka',
  'adding' => 'Dodawanie…',
  'added' => 'Dodano ✓',
  'try_again' => 'Spróbuj ponownie',
  'searching' => 'Wyszukiwanie…',
  'unavailable_brief' => 'Wyszukiwarka jest niedostępna.',
  'unavailable' => 'Wyszukiwarka jest w tej chwili niedostępna.',
  'no_products' => 'Nie znaleziono produktów.',
  'no_products_for' => 'Nie znaleziono produktów dla „%s”.',
  'nothing_found' => 'Nic nie znaleziono dla „%s”.',
  'placeholder' => 'Szukaj produktów…',
  'close_search' => 'Zamknij wyszukiwarkę',
  'product_results' => 'Wyniki wyszukiwania produktów',
  'recent_searches' => 'Ostatnie wyszukiwania',
  'clear' => 'Wyczyść',
  'start_typing' => 'Zacznij pisać, aby wyszukać produkty…',
  'sale' => 'Promocja',
  'out_of_stock' => 'Brak w magazynie',
  'pages_posts' => 'Strony i wpisy',
  'page' => 'Strona',
  'article' => 'Artykuł',
  'ms' => '%s ms',
  'powered_by' => 'Działa dzięki NitroSearch',
  'page_of' => 'Strona %1$s z %2$s',
  'prev' => '← Poprzednia',
  'next' => 'Następna →',
  'products_found' => 
  array (
    'one' => 'Znaleziono %s produkt.',
    'few' => 'Znaleziono %s produkty.',
    'many' => 'Znaleziono %s produktów.',
    'other' => 'Znaleziono %s produktów.',
  ),
  'see_all' => 
  array (
    'one' => 'Zobacz %s wynik →',
    'few' => 'Zobacz wszystkie %s wyniki →',
    'many' => 'Zobacz wszystkie %s wyników →',
    'other' => 'Zobacz wszystkie %s wyników →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s wynik dla „%2$s”',
    'few' => '%1$s wyniki dla „%2$s”',
    'many' => '%1$s wyników dla „%2$s”',
    'other' => '%1$s wyników dla „%2$s”',
  ),
  'results_count' => 
  array (
    'one' => '%s wynik',
    'few' => '%s wyniki',
    'many' => '%s wyników',
    'other' => '%s wyników',
  ),
);
