<?php
/**
 * Storefront widget labels — pt_BR.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Refinar resultados',
  'refine' => 'Refinar',
  'in_stock' => 'Em estoque',
  'on_sale' => 'Em promoção',
  'brand' => 'Marca',
  'category' => 'Categoria',
  'view' => 'Ver',
  'add_to_cart' => 'Adicionar ao carrinho',
  'adding' => 'Adicionando…',
  'added' => 'Adicionado ✓',
  'try_again' => 'Tentar novamente',
  'searching' => 'Buscando…',
  'unavailable_brief' => 'A busca está indisponível.',
  'unavailable' => 'A busca está indisponível no momento.',
  'no_products' => 'Nenhum produto encontrado.',
  'no_products_for' => 'Nenhum produto encontrado para “%s”.',
  'nothing_found' => 'Nada encontrado para “%s”.',
  'placeholder' => 'Buscar produtos…',
  'close_search' => 'Fechar busca',
  'product_results' => 'Resultados de produtos',
  'recent_searches' => 'Buscas recentes',
  'clear' => 'Limpar',
  'start_typing' => 'Comece a digitar para buscar produtos…',
  'sale' => 'Promoção',
  'out_of_stock' => 'Fora de estoque',
  'pages_posts' => 'Páginas e posts',
  'page' => 'Página',
  'article' => 'Artigo',
  'ms' => '%s ms',
  'powered_by' => 'Com tecnologia NitroSearch',
  'page_of' => 'Página %1$s de %2$s',
  'prev' => '← Anterior',
  'next' => 'Próxima →',
  'products_found' => 
  array (
    'one' => '%s produto encontrado.',
    'few' => '%s produtos encontrados.',
    'many' => '%s produtos encontrados.',
    'other' => '%s produtos encontrados.',
  ),
  'see_all' => 
  array (
    'one' => 'Ver %s resultado →',
    'few' => 'Ver todos os %s resultados →',
    'many' => 'Ver todos os %s resultados →',
    'other' => 'Ver todos os %s resultados →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s resultado para “%2$s”',
    'few' => '%1$s resultados para “%2$s”',
    'many' => '%1$s resultados para “%2$s”',
    'other' => '%1$s resultados para “%2$s”',
  ),
  'results_count' => 
  array (
    'one' => '%s resultado',
    'few' => '%s resultados',
    'many' => '%s resultados',
    'other' => '%s resultados',
  ),
);
