<?php
/**
 * Storefront widget labels — pt_PT.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Refinar resultados',
  'refine' => 'Refinar',
  'in_stock' => 'Em stock',
  'on_sale' => 'Em promoção',
  'brand' => 'Marca',
  'category' => 'Categoria',
  'view' => 'Ver',
  'add_to_cart' => 'Adicionar ao carrinho',
  'adding' => 'A adicionar…',
  'added' => 'Adicionado ✓',
  'try_again' => 'Tentar novamente',
  'searching' => 'A pesquisar…',
  'unavailable_brief' => 'A pesquisa está indisponível.',
  'unavailable' => 'A pesquisa está indisponível neste momento.',
  'no_products' => 'Não foram encontrados produtos.',
  'no_products_for' => 'Não foram encontrados produtos para «%s».',
  'nothing_found' => 'Não foi encontrado nada para «%s».',
  'placeholder' => 'Pesquisar produtos…',
  'close_search' => 'Fechar pesquisa',
  'product_results' => 'Resultados de produtos',
  'recent_searches' => 'Pesquisas recentes',
  'clear' => 'Limpar',
  'start_typing' => 'Comece a escrever para pesquisar produtos…',
  'sale' => 'Promoção',
  'out_of_stock' => 'Esgotado',
  'pages_posts' => 'Páginas e artigos',
  'page' => 'Página',
  'article' => 'Artigo',
  'ms' => '%s ms',
  'powered_by' => 'Com tecnologia NitroSearch',
  'page_of' => 'Página %1$s de %2$s',
  'prev' => '← Anterior',
  'next' => 'Seguinte →',
  'products_found' => 
  array (
    'one' => 'Foi encontrado %s produto.',
    'few' => 'Foram encontrados %s produtos.',
    'many' => 'Foram encontrados %s produtos.',
    'other' => 'Foram encontrados %s produtos.',
  ),
  'see_all' => 
  array (
    'one' => 'Ver %s resultado →',
    'few' => 'Ver todos os %s resultados →',
    'many' => 'Ver todos os %s resultados →',
    'other' => 'Ver todos os %s resultados →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s resultado para «%2$s»',
    'few' => '%1$s resultados para «%2$s»',
    'many' => '%1$s resultados para «%2$s»',
    'other' => '%1$s resultados para «%2$s»',
  ),
  'results_count' => 
  array (
    'one' => '%s resultado',
    'few' => '%s resultados',
    'many' => '%s resultados',
    'other' => '%s resultados',
  ),
);
