<?php
/**
 * Storefront widget labels — ro_RO.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Cizelează rezultatele',
  'refine' => 'Cizelează',
  'in_stock' => 'În stoc',
  'on_sale' => 'Reduceri',
  'brand' => 'Brand',
  'category' => 'Categorie',
  'view' => 'Vezi',
  'add_to_cart' => 'Adaugă în coș',
  'adding' => 'Adaug...',
  'added' => 'Adăugat ✓',
  'try_again' => 'Încearcă din nou',
  'searching' => 'Caut...',
  'unavailable_brief' => 'Căutarea este indisponibilă.',
  'unavailable' => 'Momentan căutarea este indisponibilă.',
  'no_products' => 'Nu am găsit niciun produs.',
  'no_products_for' => 'Nu am găsit niciun produs pentru „%s”.',
  'nothing_found' => 'Nu am găsit nimic pentru „%s”.',
  'placeholder' => 'Caută produse…',
  'close_search' => 'Închide căutarea',
  'product_results' => 'Rezultate pentru produse',
  'recent_searches' => 'Căutări recente',
  'clear' => 'Șterge',
  'start_typing' => 'Începe să tastezi ca să cauți produse…',
  'sale' => 'Reduceri',
  'out_of_stock' => 'Stoc epuizat',
  'pages_posts' => 'Pagini și articole',
  'page' => 'Pagină',
  'article' => 'Articol',
  'ms' => '%s ms',
  'powered_by' => 'Propulsat de NitroSearch',
  'page_of' => 'Pagina %1$s din %2$s',
  'prev' => '← Anterior',
  'next' => 'Următor →',
  'products_found' => 
  array (
    'one' => 'Am găsit un produs.',
    'few' => 'Am găsit %s produse.',
    'many' => 'Am găsit %s produse.',
    'other' => 'Am găsit %s de produse.',
  ),
  'see_all' => 
  array (
    'one' => 'Vezi un rezultat →',
    'few' => 'Vezi toate cele %s rezultate →',
    'many' => 'Vezi toate cele %s rezultate →',
    'other' => 'Vezi toate cele %s de rezultate →',
  ),
  'results_for' => 
  array (
    'one' => 'Un rezultat pentru „%2$s”',
    'few' => '%1$s rezultate pentru „%2$s”',
    'many' => '%1$s rezultate pentru „%2$s”',
    'other' => '%1$s de rezultate pentru „%2$s”',
  ),
  'results_count' => 
  array (
    'one' => 'Un rezultat',
    'few' => '%s rezultate',
    'many' => '%s rezultate',
    'other' => '%s de rezultate',
  ),
);
