<?php
/**
 * Storefront widget labels — ru_RU.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Уточнить результаты',
  'refine' => 'Уточнить',
  'in_stock' => 'В наличии',
  'on_sale' => 'Со скидкой',
  'brand' => 'Бренд',
  'category' => 'Категория',
  'view' => 'Посмотреть',
  'add_to_cart' => 'В корзину',
  'adding' => 'Добавляем…',
  'added' => 'Добавлено ✓',
  'try_again' => 'Повторить',
  'searching' => 'Ищем…',
  'unavailable_brief' => 'Поиск недоступен.',
  'unavailable' => 'Поиск сейчас недоступен.',
  'no_products' => 'Товары не найдены.',
  'no_products_for' => 'По запросу «%s» товары не найдены.',
  'nothing_found' => 'По запросу «%s» ничего не найдено.',
  'placeholder' => 'Поиск товаров…',
  'close_search' => 'Закрыть поиск',
  'product_results' => 'Найденные товары',
  'recent_searches' => 'Недавние запросы',
  'clear' => 'Очистить',
  'start_typing' => 'Начните вводить запрос, чтобы найти товары…',
  'sale' => 'Скидка',
  'out_of_stock' => 'Нет в наличии',
  'pages_posts' => 'Страницы и записи',
  'page' => 'Страница',
  'article' => 'Статья',
  'ms' => '%s мс',
  'powered_by' => 'Работает на NitroSearch',
  'page_of' => 'Страница %1$s из %2$s',
  'prev' => '← Назад',
  'next' => 'Вперёд →',
  'products_found' => 
  array (
    'one' => 'Найден %s товар.',
    'few' => 'Найдено %s товара.',
    'many' => 'Найдено %s товаров.',
    'other' => 'Найдено %s товаров.',
  ),
  'see_all' => 
  array (
    'one' => 'Показать %s результат →',
    'few' => 'Показать все %s результата →',
    'many' => 'Показать все %s результатов →',
    'other' => 'Показать все %s результатов →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s результат по запросу «%2$s»',
    'few' => '%1$s результата по запросу «%2$s»',
    'many' => '%1$s результатов по запросу «%2$s»',
    'other' => '%1$s результатов по запросу «%2$s»',
  ),
  'results_count' => 
  array (
    'one' => '%s результат',
    'few' => '%s результата',
    'many' => '%s результатов',
    'other' => '%s результатов',
  ),
);
