<?php
/**
 * Storefront widget labels — sv_SE.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Förfina resultaten',
  'refine' => 'Förfina',
  'in_stock' => 'I lager',
  'on_sale' => 'På rea',
  'brand' => 'Varumärke',
  'category' => 'Kategori',
  'view' => 'Visa',
  'add_to_cart' => 'Lägg i varukorg',
  'adding' => 'Lägger till…',
  'added' => 'Tillagd ✓',
  'try_again' => 'Försök igen',
  'searching' => 'Söker…',
  'unavailable_brief' => 'Sökningen är inte tillgänglig.',
  'unavailable' => 'Sökningen är inte tillgänglig just nu.',
  'no_products' => 'Inga produkter hittades.',
  'no_products_for' => 'Inga produkter hittades för ”%s”.',
  'nothing_found' => 'Inget hittades för ”%s”.',
  'placeholder' => 'Sök produkter…',
  'close_search' => 'Stäng sökningen',
  'product_results' => 'Produktresultat',
  'recent_searches' => 'Senaste sökningar',
  'clear' => 'Rensa',
  'start_typing' => 'Börja skriva för att söka produkter…',
  'sale' => 'Rea',
  'out_of_stock' => 'Slut i lager',
  'pages_posts' => 'Sidor och inlägg',
  'page' => 'Sida',
  'article' => 'Artikel',
  'ms' => '%s ms',
  'powered_by' => 'Drivs av NitroSearch',
  'page_of' => 'Sida %1$s av %2$s',
  'prev' => '← Föregående',
  'next' => 'Nästa →',
  'products_found' => 
  array (
    'one' => '%s produkt hittades.',
    'few' => '%s produkter hittades.',
    'many' => '%s produkter hittades.',
    'other' => '%s produkter hittades.',
  ),
  'see_all' => 
  array (
    'one' => 'Visa %s resultat →',
    'few' => 'Visa alla %s resultat →',
    'many' => 'Visa alla %s resultat →',
    'other' => 'Visa alla %s resultat →',
  ),
  'results_for' => 
  array (
    'other' => '%1$s resultat för ”%2$s”',
  ),
  'results_count' => 
  array (
    'other' => '%s resultat',
  ),
);
