<?php
/**
 * Storefront widget labels — tr_TR.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Sonuçları daralt',
  'refine' => 'Daralt',
  'in_stock' => 'Stokta var',
  'on_sale' => 'İndirimde',
  'brand' => 'Marka',
  'category' => 'Kategori',
  'view' => 'Görüntüle',
  'add_to_cart' => 'Sepete ekle',
  'adding' => 'Ekleniyor…',
  'added' => 'Eklendi ✓',
  'try_again' => 'Yeniden dene',
  'searching' => 'Aranıyor…',
  'unavailable_brief' => 'Arama kullanılamıyor.',
  'unavailable' => 'Arama şu anda kullanılamıyor.',
  'no_products' => 'Ürün bulunamadı.',
  'no_products_for' => '“%s” için ürün bulunamadı.',
  'nothing_found' => '“%s” için hiçbir şey bulunamadı.',
  'placeholder' => 'Ürün ara…',
  'close_search' => 'Aramayı kapat',
  'product_results' => 'Ürün sonuçları',
  'recent_searches' => 'Son aramalar',
  'clear' => 'Temizle',
  'start_typing' => 'Ürün aramak için yazmaya başlayın…',
  'sale' => 'İndirim',
  'out_of_stock' => 'Stokta yok',
  'pages_posts' => 'Sayfalar ve yazılar',
  'page' => 'Sayfa',
  'article' => 'Yazı',
  'ms' => '%s ms',
  'powered_by' => 'NitroSearch gücüyle',
  'page_of' => 'Sayfa %1$s / %2$s',
  'prev' => '← Önceki',
  'next' => 'Sonraki →',
  'products_found' => 
  array (
    'other' => '%s ürün bulundu.',
  ),
  'see_all' => 
  array (
    'other' => '%s sonucun tamamını gör →',
  ),
  'results_for' => 
  array (
    'other' => '“%2$s” için %1$s sonuç',
  ),
  'results_count' => 
  array (
    'other' => '%s sonuç',
  ),
);
