<?php
/**
 * Storefront widget labels — uk.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Уточнити результати',
  'refine' => 'Уточнити',
  'in_stock' => 'В наявності',
  'on_sale' => 'Зі знижкою',
  'brand' => 'Бренд',
  'category' => 'Категорія',
  'view' => 'Переглянути',
  'add_to_cart' => 'Додати в кошик',
  'adding' => 'Додаємо…',
  'added' => 'Додано ✓',
  'try_again' => 'Спробувати ще раз',
  'searching' => 'Шукаємо…',
  'unavailable_brief' => 'Пошук недоступний.',
  'unavailable' => 'Пошук зараз недоступний.',
  'no_products' => 'Товарів не знайдено.',
  'no_products_for' => 'За запитом «%s» товарів не знайдено.',
  'nothing_found' => 'За запитом «%s» нічого не знайдено.',
  'placeholder' => 'Шукати товари…',
  'close_search' => 'Закрити пошук',
  'product_results' => 'Знайдені товари',
  'recent_searches' => 'Нещодавні запити',
  'clear' => 'Очистити',
  'start_typing' => 'Почніть вводити, щоб шукати товари…',
  'sale' => 'Розпродаж',
  'out_of_stock' => 'Немає в наявності',
  'pages_posts' => 'Сторінки й записи',
  'page' => 'Сторінка',
  'article' => 'Стаття',
  'ms' => '%s мс',
  'powered_by' => 'Працює на NitroSearch',
  'page_of' => 'Сторінка %1$s з %2$s',
  'prev' => '← Назад',
  'next' => 'Далі →',
  'products_found' => 
  array (
    'one' => 'Знайдено %s товар.',
    'few' => 'Знайдено %s товари.',
    'many' => 'Знайдено %s товарів.',
    'other' => 'Знайдено %s товарів.',
  ),
  'see_all' => 
  array (
    'one' => 'Переглянути %s результат →',
    'few' => 'Переглянути всі %s результати →',
    'many' => 'Переглянути всі %s результатів →',
    'other' => 'Переглянути всі %s результатів →',
  ),
  'results_for' => 
  array (
    'one' => '%1$s результат за запитом «%2$s»',
    'few' => '%1$s результати за запитом «%2$s»',
    'many' => '%1$s результатів за запитом «%2$s»',
    'other' => '%1$s результатів за запитом «%2$s»',
  ),
  'results_count' => 
  array (
    'one' => '%s результат',
    'few' => '%s результати',
    'many' => '%s результатів',
    'other' => '%s результатів',
  ),
);
