<?php
/**
 * Storefront widget labels — vi.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => 'Lọc kết quả',
  'refine' => 'Lọc',
  'in_stock' => 'Còn hàng',
  'on_sale' => 'Đang giảm giá',
  'brand' => 'Thương hiệu',
  'category' => 'Danh mục',
  'view' => 'Xem',
  'add_to_cart' => 'Thêm vào giỏ hàng',
  'adding' => 'Đang thêm…',
  'added' => 'Đã thêm ✓',
  'try_again' => 'Thử lại',
  'searching' => 'Đang tìm kiếm…',
  'unavailable_brief' => 'Tìm kiếm không khả dụng.',
  'unavailable' => 'Tìm kiếm hiện không khả dụng ngay lúc này.',
  'no_products' => 'Không tìm thấy sản phẩm nào.',
  'no_products_for' => 'Không tìm thấy sản phẩm nào cho “%s”.',
  'nothing_found' => 'Không tìm thấy gì cho “%s”.',
  'placeholder' => 'Tìm kiếm sản phẩm…',
  'close_search' => 'Đóng tìm kiếm',
  'product_results' => 'Kết quả sản phẩm',
  'recent_searches' => 'Tìm kiếm gần đây',
  'clear' => 'Xóa',
  'start_typing' => 'Bắt đầu gõ để tìm kiếm sản phẩm…',
  'sale' => 'Giảm giá',
  'out_of_stock' => 'Hết hàng',
  'pages_posts' => 'Trang & bài viết',
  'page' => 'Trang',
  'article' => 'Bài viết',
  'ms' => '%s ms',
  'powered_by' => 'Được cung cấp bởi NitroSearch',
  'page_of' => 'Trang %1$s / %2$s',
  'prev' => '← Trước',
  'next' => 'Tiếp →',
  'products_found' => 
  array (
    'other' => 'Đã tìm thấy %s sản phẩm.',
  ),
  'see_all' => 
  array (
    'other' => 'Xem tất cả %s kết quả →',
  ),
  'results_for' => 
  array (
    'other' => '%1$s kết quả cho “%2$s”',
  ),
  'results_count' => 
  array (
    'other' => '%s kết quả',
  ),
);
