<?php
/**
 * Storefront widget labels — zh_CN.
 *
 * GENERATED by bin/sync-widget-labels.php from the reviewed gettext
 * catalogues in the WooCommerce plugin. Do not edit by hand: the next
 * run overwrites it, and a hand edit here is a correction that never
 * reaches the other platforms. Fix the .po and regenerate.
 *
 * @package NitroSearch
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

return array (
  'refine_results' => '筛选结果',
  'refine' => '筛选',
  'in_stock' => '有货',
  'on_sale' => '促销',
  'brand' => '品牌',
  'category' => '分类',
  'view' => '查看',
  'add_to_cart' => '加入购物车',
  'adding' => '正在加入…',
  'added' => '已加入 ✓',
  'try_again' => '重试',
  'searching' => '正在搜索…',
  'unavailable_brief' => '搜索不可用。',
  'unavailable' => '搜索目前不可用。',
  'no_products' => '未找到相关商品。',
  'no_products_for' => '未找到与“%s”相关的商品。',
  'nothing_found' => '未找到与“%s”相关的内容。',
  'placeholder' => '搜索商品…',
  'close_search' => '关闭搜索',
  'product_results' => '商品结果',
  'recent_searches' => '最近搜索',
  'clear' => '清除',
  'start_typing' => '开始输入即可搜索商品…',
  'sale' => '特价',
  'out_of_stock' => '缺货',
  'pages_posts' => '页面与文章',
  'page' => '页面',
  'article' => '文章',
  'ms' => '%s毫秒',
  'powered_by' => '由NitroSearch提供技术支持',
  'page_of' => '第%1$s页，共%2$s页',
  'prev' => '← 上一页',
  'next' => '下一页 →',
  'products_found' => 
  array (
    'other' => '已找到%s个商品。',
  ),
  'see_all' => 
  array (
    'other' => '查看全部%s条结果 →',
  ),
  'results_for' => 
  array (
    'other' => '找到%1$s条与“%2$s”相关的结果',
  ),
  'results_count' => 
  array (
    'other' => '%s条结果',
  ),
);
